In [1]:
import numpy as np

1. Исследовать на линейную зависимость:
$$f_{1}(x)=e^{x}, f_{2}(x)=1, f_{3}(x)=x+1, f_{4}(x)=x-e^{x}.$$

$f_{4}(x)=f_{3}(x)-f_{1}(x)-f_{2}(x)$, то есть вектор $f_{4}(x)$ — линейная комбинация векторов $f_{1}(x)$,$f_{2}(x)$  и $f_{3}(x)$, из чего можно сделать вывод, что представленные вектора линейно зависимы.

__2.__ Исследовать на линейную зависимость:
$$f_{1}(x)=2, f_{2}(x)=x, f_{3}(x)=x^{2}, f_{4}(x)=(x+1)^{2}=x^{2}+2x+1.$$

$f_{4}(x)=f_{3}(x)+2f_{2}(x)+f_{1}(x)*1/2$, то есть вектор $f_{4}(x)$ — линейная комбинация векторов $f_{1}(x)$,$f_{2}(x)$  и $f_{3}(x)$, из чего можно сделать вывод, что представленные вектора линейно зависимы.

__3.__ Найти координаты вектора $x = (2, 3, 5)\in \mathbb{R}^{3}$ в базисе $b_{1}=(0, 0, 10)$, $b_{2}=(2, 0, 0)$, $b_{3}=(0, 1, 0)$

In [4]:
b1 = np.array([0,0,10])
b2 = np.array([2,0,0])
b3 = np.array([0,1,0])
x = np.array([2,3,5])

In [6]:
A = np.array([b1, b2, b3]).T
A

array([[ 0,  2,  0],
       [ 0,  0,  1],
       [10,  0,  0]])

In [7]:
A_1 = np.linalg.inv(A)
A_1

array([[0. , 0. , 0.1],
       [0.5, 0. , 0. ],
       [0. , 1. , 0. ]])

In [8]:
L = np.dot(A_1, x)
L

array([0.5, 1. , 3. ])