In [1]:
import numpy as np

1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .



Для того, чтобы произведение матриц было определено, необходимо, чтобы количество столбцов в первой матрице соответствовало количеству строк во второй.

a) произведение матриц неопределено

б) произведение матриц определено, итоговая матрица имеет размерность 2×3

в) произведение матриц определено, итоговая матрица имеет размерность 8×8

г) произведение матриц определено, итоговая матрица имеет размерность 4×4


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$



In [4]:
A = np.array([[1, -2] , [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'сумма матриц:\n{A + B}')
print(f'произведение матриц:\n{np.dot(A, B)}')

сумма матриц:
[[ 5 -3]
 [ 3  5]]
произведение матриц:
[[  4 -11]
 [ 12  -3]]




__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
 


In [6]:
A = np.array([[1, 7] , [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
A_B_C = 3 * A - 2 * B + 4 * C
A_B_C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.



In [10]:
A = np.array([[4, 1] , [5, -2], [2, 3]])
print(np.dot(A, A.T))
print(np.dot(A.T, A))


[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]
