In [1]:
import numpy as np

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$



In [4]:
a = np.array([[-1,-6], [2, 6]])
a

array([[-1, -6],
       [ 2,  6]])

In [5]:
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.



Найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим

$$\begin{cases}
-x_{1}+0\cdot x_{2}= x_{1}, \\
0\cdot x_{1}-x_{2}= x_{2}.
\end{cases}$$ 


$$\begin{cases}
 - x_{1} = x_{1}, \\
 - x_{2} = x_{2}.
\end{cases}$$ 


Очевидно, что при лямбда равном -1, система имеет множество решений

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



In [7]:
a = np.array([[1, 1], [-1, 3]])
x = np.array([[1], [1]])
z = np.dot(a, x)
z / 2

array([[1.],
       [1.]])

In [ ]:
Таким образом лямбда = 2 и вектор х является собственным вектором линейного оператора А

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

In [16]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
x = np.array([[3], [-3], [-4]])
z = np.dot(a, x)
z // 3
#np.linalg.det(a)

array([[-3],
       [ 3],
       [-4]], dtype=int32)

вектор x не является собственным вектором